services:

  database:
    image: mariadb
    container_name: mariadb-blog
    ports:
      - 3306:3306
    volumes:
      - db-data:/var/lib/mysql/data:rw
    environment:
      MARIADB_ALLOW_EMPTY_ROOT_PASSWORD: 'yes'
      MARIADB_DATABASE: 'blog_db'
    networks:
      - webdev

  phpmyadmin:
    image: phpmyadmin
    container_name: phpmyadmin-blog
    depends_on:
      - database
    ports:
      - 8085:80
    environment:
      PMA_HOST: database
      MYSQL_ROOT_PASSWORD: 'root'
    networks:
      - webdev

  rabbitmq:
    image: rabbitmq:3.7-management
    container_name: rabbitmq-blog
    ports: [ 5672, 15672 ]
    networks:
      - webdev

  ###> symfony/mailer ###
  mailer:
    image: axllent/mailpit
    container_name: mailpit-blog
    ports:
      - "1025"
      - "8025"
    environment:
      MP_SMTP_AUTH_ACCEPT_ANY: 1
      MP_SMTP_AUTH_ALLOW_INSECURE: 1
    networks:
      - webdev
###< symfony/mailer ###

volumes:
  db-data:
networks:
  webdev:
